### ISSUE TITLE
`coreygirard/elm-nonempty-list` pollutes dependencies with a specific `elm-explorations/test` version.

### ISSUE THREAD

**Issue by SiriusStarr** [axelerator/fancy-forms#2]
Due to a bug in the `elm.json` of that package, anyone using fancy forms gets locked into an out-dated test version.  I opened a PR to fix it here: https://github.com/coreygirard/elm-nonempty-list/pull/2 but barring that being merged, it would be easy enough to switch to any of a number of other non-empty list packages without this problem that are equivalent.  (I'd be happy to throw together a PR for that if you so desire.)

**Comment by axelerator** [comment]
Oh wow 🤯
Sorry for that and the late response. And thanks 💯 for the PR, will fix and release immediately 🙏

**Comment by axelerator** [comment]
Ahh I see that's actually no in my fancy_forms package but the nonempty list one I'm _using_ 🙈

**Comment by axelerator** [comment]
Was a bit more of a detour than I had hoped, but should be fixed now in v7.0.0
